table dim_parameter
	lineageTag: e0e8d7d5-4057-4a72-9e00-b2d7bccfbbdc
	sourceLineageTag: [dbo].[dim_parameter]

	measure 'Pollutant Display Name' =
			
			SWITCH(
			    SELECTEDVALUE(dim_parameter[parameter_name]),
			    "carbon monoxide", "Carbon Monoxide",
			    "Nitrogen dioxide (N02)", "Nitrogen Dioxide",
			    "Ozone", "Ozone",
			    "PM10 Total 0-10um STP", "PM 10",
			    "PM2.5 - Local Conditions", "PM 2.5",
			    "Sulfur dioxide", "Sulfur Dioxide",
			    SELECTEDVALUE(dim_parameter[parameter_name])
			)
		lineageTag: e1aefce4-a9ab-4dba-beb7-3719caa3d13d

		changedProperty = Name

	measure 'Exposure Score' =
			
			[Unhealthy Day Count] * SUM(dim_location[population])
		formatString: 0
		lineageTag: 6c790a04-657c-4ecf-b900-0d3dca1c9623

		changedProperty = Name

	measure '% of US Exposure' =
			
			DIVIDE(
			    [Exposure Score],
			    CALCULATE(
			        [Exposure Score],
			        ALL(dim_location[state_name])
			    )
			)
		lineageTag: fda39bd3-32b4-4e6f-8571-914caa7aaeed

		changedProperty = Name

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column parameter_key
		dataType: int64
		formatString: 0
		lineageTag: e65a3cce-bd24-41f6-a8c5-d59be1af058a
		sourceLineageTag: parameter_key
		summarizeBy: none
		sourceColumn: parameter_key

		annotation SummarizationSetBy = Automatic

	column parameter_code
		dataType: string
		lineageTag: a1bc2b70-b2d8-4548-92c4-9778af4e0f37
		sourceLineageTag: parameter_code
		summarizeBy: none
		sourceColumn: parameter_code

		annotation SummarizationSetBy = Automatic

	column parameter_name
		dataType: string
		lineageTag: 9b1cd5fe-b503-4a95-a1eb-d69199151470
		sourceLineageTag: parameter_name
		summarizeBy: none
		sourceColumn: parameter_name

		annotation SummarizationSetBy = Automatic

	column unit_of_measurement
		dataType: string
		lineageTag: d59625d4-ba0b-4807-b56f-7c6cb46519c1
		sourceLineageTag: unit_of_measurement
		summarizeBy: none
		sourceColumn: unit_of_measurement

		annotation SummarizationSetBy = Automatic

	column category
		dataType: string
		lineageTag: 3f38a6f4-a2e7-4d25-9e92-5b761a1eb366
		sourceLineageTag: category
		summarizeBy: none
		sourceColumn: category

		annotation SummarizationSetBy = Automatic

	partition dim_parameter = entity
		mode: directLake
		source
			entityName: dim_parameter
			schemaName: dbo
			expressionSource: 'DirectLake - team2_WH'

